- name: use playbook
  hosts: server
  become: true

  vars:
    etc_hosts:
      - 192.168.57.101 grafana.local.com
      - 192.168.57.101 loki.local.com

    cert_domain: local.com
    cert_insecure: 1

    loki_url: http://192.168.57.101:3100
    
    prometheus_username: test
    prometheus_password: test
    prometheus_password_hash: "{{prometheus_password | password_hash('bcrypt')}}"

    node_exporter_username: test
    node_exporter_password: test
    node_exporter_password_hash: "{{node_exporter_password | password_hash('bcrypt')}}"
    
    node_exporter_targets:
      - 192.168.57.101:9100
      - 192.168.57.102:9100

    loki_username: test
    loki_password: test
    loki_password_hash: "{{loki_password | password_hash('bcrypt')}}"
    loki_tentant: test

    docker_username: vagrant

    timezone: Asia/Ho_Chi_Minh

  roles:
    - role: common
    - role: auditd
    - role: prometheus
    - role: loki
    - role: docker
    - role: loki-driver
    - role: nginx-grafana-compose
    - role: node-exporter-compose
    - role: promtail-compose